const majorNames=['愚人','魔术师','女祭司','皇后','皇帝','教皇','恋人','战车','力量','隐者','命运之轮','正义','倒吊人','死神','节制','恶魔','高塔','星星','月亮','太阳','审判','世界'];
const majorEn=['The Fool','The Magician','The High Priestess','The Empress','The Emperor','The Hierophant','The Lovers','The Chariot','Strength','The Hermit','Wheel of Fortune','Justice','The Hanged Man','Death','Temperance','The Devil','The Tower','The Star','The Moon','The Sun','Judgement','The World'];
const majorSymbols=['∞','Ⅰ','☽','♀','♜','⚜','Ⅵ','♞','♌','☄','✺','⚖','♆','♱','⚗','♑','ϟ','☆','☾','☀','♢','◎'];
const majorMeanings=[['启程','自由','信任'],['创造','意志','显化'],['直觉','静默','内在'],['丰盛','滋养','创造'],['秩序','责任','边界'],['传统','信念','指引'],['连接','选择','价值'],['行动','掌控','前进'],['勇气','温柔','韧性'],['独处','寻找','智慧'],['转机','周期','机缘'],['平衡','真相','因果'],['暂停','换位','臣服'],['结束','蜕变','新生'],['调和','耐心','疗愈'],['执着','欲望','束缚'],['突变','真相','释放'],['希望','灵感','宁静'],['迷雾','潜意识','敏感'],['喜悦','成功','活力'],['觉醒','召唤','复盘'],['完成','整合','圆满']];
const suits={wands:{name:'权杖',en:'Wands',symbol:'♧',glow:'#76543d',theme:'行动、热情与创造力'},cups:{name:'圣杯',en:'Cups',symbol:'♕',glow:'#3f6471',theme:'情感、关系与直觉'},swords:{name:'宝剑',en:'Swords',symbol:'†',glow:'#536270',theme:'思想、沟通与挑战'},pentacles:{name:'星币',en:'Pentacles',symbol:'✥',glow:'#65704a',theme:'物质、事业与稳定'}};
const ranks=['王牌','二','三','四','五','六','七','八','九','十','侍从','骑士','王后','国王'];
const rankEn=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'];
const rankWords=[['开始','潜能'],['平衡','选择'],['协作','成长'],['稳固','休整'],['冲突','变化'],['进展','分享'],['评估','坚持'],['速度','磨练'],['成熟','考验'],['完成','承担'],['讯息','学习'],['追寻','行动'],['包容','掌握'],['领导','成就']];
const cards=majorNames.map((name,i)=>({name,en:majorEn[i],suit:'major',suitName:'大阿卡那',symbol:majorSymbols[i],glow:['#62684a','#735c3e','#495970'][i%3],keywords:majorMeanings[i],meaning:`${name}提醒你关注${majorMeanings[i].join('、')}。此刻不必急着得到唯一答案，先诚实地看见正在发生的一切。`,reversed:`逆位时，它提示相关能量可能被压抑、延迟或过度使用。放慢脚步，重新校准内在与行动。`}));
Object.entries(suits).forEach(([key,s])=>ranks.forEach((rank,i)=>cards.push({name:`${s.name}${rank}`,en:`${rankEn[i]} of ${s.en}`,suit:key,suitName:s.name,symbol:s.symbol,glow:s.glow,keywords:[...rankWords[i],s.theme.split('、')[0]],meaning:`${s.name}${rank}聚焦于${s.theme}。${rankWords[i][0]}的能量正在显现，邀请你以${rankWords[i][1]}的态度回应当下。`,reversed:`逆位提示${rankWords[i][0]}的进程受到阻滞。避免勉强推进，先照顾真实需求，再寻找更稳妥的表达。`})));
const spreads={single:{name:'一张牌 · 每日指引',count:1,positions:['当下的指引']},three:{name:'时间之流',count:3,positions:['过去的影响','此刻的课题','未来的可能']},choice:{name:'抉择之路',count:5,positions:['现状','选择 A','A 的启示','选择 B','B 的启示']},celtic:{name:'凯尔特十字',count:10,positions:['核心现状','眼前挑战','意识目标','潜在根基','近期过去','近期发展','你的状态','外部环境','希望与恐惧','最终趋势']}};
let selectedSpread='single', activeSuit='all';
const deckGrid=document.querySelector('#deckGrid');
function cardArt(card){return `<div class="card-art" style="--glow:${card.glow}"><span>${card.symbol}</span></div>`}
function renderDeck(){const q=document.querySelector('#cardSearch').value.trim().toLowerCase();const list=cards.filter(c=>(activeSuit==='all'||c.suit===activeSuit)&&(!q||`${c.name}${c.en}${c.keywords.join('')}`.toLowerCase().includes(q)));deckGrid.innerHTML=list.map((c)=>`<button class="deck-item" data-index="${cards.indexOf(c)}">${cardArt(c)}<h3>${c.name}</h3><small>${c.en}</small></button>`).join('');}
renderDeck();
document.querySelectorAll('.nav-link').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===btn.dataset.view));scrollTo({top:0,behavior:'smooth'});if(btn.dataset.view==='deck')renderDeck()});
document.querySelectorAll('.spread-card').forEach(btn=>btn.onclick=()=>{selectedSpread=btn.dataset.spread;document.querySelectorAll('.spread-card').forEach(x=>x.classList.toggle('selected',x===btn))});
const question=document.querySelector('#question');question.oninput=()=>document.querySelector('.counter').textContent=`${question.value.length} / 80`;
document.querySelectorAll('.filters button').forEach(btn=>btn.onclick=()=>{activeSuit=btn.dataset.suit;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===btn));renderDeck()});
document.querySelector('#cardSearch').oninput=renderDeck;
function openModal(id){const m=document.querySelector(id);m.classList.add('open');m.setAttribute('aria-hidden','false')}
function closeModal(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}
document.querySelectorAll('.modal').forEach(m=>{m.querySelector('.close').onclick=()=>closeModal(m);m.onclick=e=>{if(e.target===m)closeModal(m)}});
deckGrid.onclick=e=>{const item=e.target.closest('.deck-item');if(!item)return;const c=cards[item.dataset.index];document.querySelector('#cardContent').innerHTML=`<div class="card-detail">${cardArt(c)}<div class="card-copy"><span class="eyebrow">${c.suitName}</span><h2>${c.name}</h2><span class="en">${c.en.toUpperCase()}</span><div class="keywords">${c.keywords.map(k=>`<span>${k}</span>`).join('')}</div><h4>正位解读</h4><p>${c.meaning}</p><h4>逆位解读</h4><p>${c.reversed}</p></div></div>`;openModal('#cardModal')};
function drawReading(){const spread=spreads[selectedSpread],pool=[...cards],draw=[];for(let i=0;i<spread.count;i++){const c=pool.splice(Math.floor(Math.random()*pool.length),1)[0];draw.push({...c,reversed:Math.random()<.28})}const topic=question.value.trim()?`关于“${question.value.trim()}”`:'关于你此刻的状态';const messages=draw.map((c,i)=>`${spread.positions[i]}出现${c.name}${c.reversed?'逆位':'正位'}，提示${c.keywords.slice(0,2).join('与')}`).join('；');document.querySelector('#readingContent').innerHTML=`<div class="draw-header"><span class="eyebrow">YOUR READING</span><h2>${spread.name}</h2><p>${topic}</p></div><div class="drawn-cards">${draw.map((c,i)=>`<div class="draw-card ${c.reversed?'reversed':''}">${cardArt(c)}<h3>${c.name}</h3><small>${spread.positions[i]} · ${c.reversed?'逆位':'正位'}</small></div>`).join('')}</div><div class="result"><h3>✦ 综合解读</h3><p>${messages}。这些牌共同邀请你：尊重已经浮现的感受，在可控的小事上迈出一步，同时为尚未清晰的部分保留空间。塔罗呈现的是此刻的可能性，而你始终拥有选择方向的自由。</p></div><div class="reading-actions"><button id="redraw">重新抽牌</button></div>`;openModal('#readingModal');document.querySelector('#redraw').onclick=drawReading}
document.querySelector('#startReading').onclick=()=>{const btn=document.querySelector('#startReading span');btn.textContent='正在洗牌…';setTimeout(()=>{btn.textContent='开始洗牌';drawReading()},700)};
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(closeModal)});
