const majorNames=['愚人','魔术师','女祭司','皇后','皇帝','教皇','恋人','战车','力量','隐者','命运之轮','正义','倒吊人','死神','节制','恶魔','高塔','星星','月亮','太阳','审判','世界'];
const majorEn=['The Fool','The Magician','The High Priestess','The Empress','The Emperor','The Hierophant','The Lovers','The Chariot','Strength','The Hermit','Wheel of Fortune','Justice','The Hanged Man','Death','Temperance','The Devil','The Tower','The Star','The Moon','The Sun','Judgement','The World'];
const majorSymbols=['∞','Ⅰ','☽','♀','♜','⚜','Ⅵ','♞','♌','☄','✺','⚖','♆','♱','⚗','♑','ϟ','☆','☾','☀','♢','◎'];
const majorMeanings=[['启程','自由','信任'],['创造','意志','显化'],['直觉','静默','内在'],['丰盛','滋养','创造'],['秩序','责任','边界'],['传统','信念','指引'],['连接','选择','价值'],['行动','掌控','前进'],['勇气','温柔','韧性'],['独处','寻找','智慧'],['转机','周期','机缘'],['平衡','真相','因果'],['暂停','换位','臣服'],['结束','蜕变','新生'],['调和','耐心','疗愈'],['执着','欲望','束缚'],['突变','真相','释放'],['希望','灵感','宁静'],['迷雾','潜意识','敏感'],['喜悦','成功','活力'],['觉醒','召唤','复盘'],['完成','整合','圆满']];
const suits={wands:{name:'权杖',en:'Wands',symbol:'♧',glow:'#76543d',theme:'行动、热情与创造力'},cups:{name:'圣杯',en:'Cups',symbol:'♕',glow:'#3f6471',theme:'情感、关系与直觉'},swords:{name:'宝剑',en:'Swords',symbol:'†',glow:'#536270',theme:'思想、沟通与挑战'},pentacles:{name:'星币',en:'Pentacles',symbol:'✥',glow:'#65704a',theme:'物质、事业与稳定'}};
const ranks=['王牌','二','三','四','五','六','七','八','九','十','侍从','骑士','王后','国王'];
const rankEn=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'];
const rankWords=[['开始','潜能'],['平衡','选择'],['协作','成长'],['稳固','休整'],['冲突','变化'],['进展','分享'],['评估','坚持'],['速度','磨练'],['成熟','考验'],['完成','承担'],['讯息','学习'],['追寻','行动'],['包容','掌握'],['领导','成就']];
const cards=majorNames.map((name,i)=>({name,en:majorEn[i],suit:'major',suitName:'大阿卡那',symbol:majorSymbols[i],glow:['#62684a','#735c3e','#495970'][i%3],keywords:majorMeanings[i],meaning:`${name}提醒你关注${majorMeanings[i].join('、')}。此刻不必急着得到唯一答案，先诚实地看见正在发生的一切。`,reversed:`逆位时，它提示相关能量可能被压抑、延迟或过度使用。放慢脚步，重新校准内在与行动。`}));
Object.entries(suits).forEach(([key,s])=>ranks.forEach((rank,i)=>cards.push({name:`${s.name}${rank}`,en:`${rankEn[i]} of ${s.en}`,suit:key,suitName:s.name,symbol:s.symbol,glow:s.glow,keywords:[...rankWords[i],s.theme.split('、')[0]],meaning:`${s.name}${rank}聚焦于${s.theme}。${rankWords[i][0]}的能量正在显现，邀请你以${rankWords[i][1]}的态度回应当下。`,reversed:`逆位提示${rankWords[i][0]}的进程受到阻滞。避免勉强推进，先照顾真实需求，再寻找更稳妥的表达。`})));
const spreads={single:{name:'一张牌 · 每日指引',count:1,positions:['当下的指引']},three:{name:'时间之流',count:3,positions:['过去的影响','此刻的课题','未来的可能']},choice:{name:'抉择之路',count:2,positions:['方向 A','方向 B']},celtic:{name:'凯尔特十字',count:10,positions:['核心现状','眼前挑战','意识目标','潜在根基','近期过去','近期发展','你的状态','外部环境','希望与恐惧','最终趋势']}};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
let selectedSpread='single',activeSuit='all',filteredCards=[...cards],deckIndex=0,detailContext=cards,detailIndex=0,currentReading=[],currentChoices=[],isAnimating=false,readingPhase='idle',revealedCount=0;
const rotations=[-11,6,-3,9,-7,4,12,-5,7,-9];
function art(card,extra=''){const cardNumber=card.sourceIndex??cards.indexOf(card);return `<div class="card-art ${extra}" style="--glow:${card.glow}"><div class="card-frame"><span class="card-number">${String(cardNumber).padStart(2,'0')}</span><b>${card.symbol}</b><i>${card.suitName}</i></div></div>`}
function randomDraw(count){const pool=[...cards],draw=[];for(let i=0;i<count;i++){const card=pool.splice(Math.floor(Math.random()*pool.length),1)[0];draw.push({...card,isReversed:Math.random()<.28,sourceIndex:cards.indexOf(card)})}return draw}
function setView(name){$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===name));if(name==='deck')renderDeck();scrollTo({top:0,behavior:'smooth'})}
$$('.nav-link').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));
$$('.spread-option').forEach(btn=>btn.addEventListener('click',()=>{selectedSpread=btn.dataset.spread;$$('.spread-option').forEach(x=>x.classList.toggle('selected',x===btn));$('.home-stage').dataset.layout=selectedSpread;$('#selectedSpreadLabel').textContent=spreads[selectedSpread].name.split(' · ')[0];$('#spreadHint').textContent={single:'为当下提供一个清晰视角',three:'看见过去、此刻与未来的脉络',choice:'让两个方向分别向你展开',celtic:'从十个角度进行完整扫描'}[selectedSpread]}));
$('.home-stage').addEventListener('pointermove',e=>{const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width-.5,y=(e.clientY-rect.top)/rect.height-.5;e.currentTarget.style.setProperty('--px',x);e.currentTarget.style.setProperty('--py',y)});
$('.home-stage').addEventListener('pointerleave',e=>{e.currentTarget.style.setProperty('--px',0);e.currentTarget.style.setProperty('--py',0)});

function openScene(scene){scene.classList.add('open');scene.setAttribute('aria-hidden','false');document.body.classList.add('scene-open')}
function closeScene(scene){scene.classList.remove('open');scene.setAttribute('aria-hidden','true');if(!$('.detail-scene.open')&&!$('.reading-scene.open')&&!$('.ritual.open'))document.body.classList.remove('scene-open')}
$('#startReading').addEventListener('click',openReading);
$('.scene-close').addEventListener('click',()=>closeScene($('#readingScene')));
const phaseOrder=['transition','shuffle','spread','selection','reveal','interpretation'];
function setReadingPhase(phase,message){readingPhase=phase;$('#readingScene').dataset.phase=phase;$('#readingTopic').textContent=message;$$('#phaseRail i').forEach((item,i)=>item.classList.toggle('active',i===phaseOrder.indexOf(phase)))}
async function openReading(){if(isAnimating)return;currentReading=randomDraw(spreads[selectedSpread].count);revealedCount=0;$('#readingSpreadName').textContent=spreads[selectedSpread].name.toUpperCase();$('#readingCards').className=`reading-cards layout-${selectedSpread}`;$('#readingCards').innerHTML='';$('#readingSummary').innerHTML='';$('#ritualDeck').innerHTML=Array.from({length:7},(_,i)=>`<i style="--i:${i}"></i>`).join('');openScene($('#readingScene'));isAnimating=true;setReadingPhase('transition','正在离开日常界面');await wait(520);setReadingPhase('shuffle','牌正在聚拢、交错');await wait(1450);setReadingPhase('spread','牌正在寻找各自的位置');renderReading();await wait(900+currentReading.length*70);setReadingPhase('selection','点击任意牌，亲手将它翻开');isAnimating=false}
function readingCardMarkup(c,i){return `<button class="floating-card dealt" data-read-index="${i}" style="--rot:${rotations[i%rotations.length]}deg;--delay:${i*85}ms;--z:${20+i}" aria-label="${spreads[selectedSpread].positions[i]}，点击揭牌"><span class="flip-shell"><span class="card-face card-back"><i>✦</i></span><span class="card-face card-front ${c.isReversed?'is-reversed':''}">${art(c)}</span></span><span class="position-label"><b>${String(i+1).padStart(2,'0')}</b>${spreads[selectedSpread].positions[i]}</span><span class="card-label"><b>${c.name}</b><i>${c.en} · ${c.isReversed?'逆位':'正位'}</i></span></button>`}
function renderReading(){const area=$('#readingCards');area.innerHTML=currentReading.map(readingCardMarkup).join('');requestAnimationFrame(()=>requestAnimationFrame(()=>$$('.floating-card',area).forEach(x=>x.classList.remove('dealt'))))}
function revealCard(card){if(card.classList.contains('revealed')||!['selection','reveal'].includes(readingPhase))return;setReadingPhase('reveal','牌面正在显现');card.classList.add('revealed');revealedCount++;if(revealedCount===currentReading.length)setTimeout(showInterpretation,700)}
function showInterpretation(){setReadingPhase('interpretation','阅读牌与牌之间的联系');const spread=spreads[selectedSpread];$('#readingSummary').innerHTML=`<span>COMBINED SIGNAL</span><p>${currentReading.map((c,i)=>`${spread.positions[i]}：${c.name}${c.isReversed?'逆位':'正位'}指向${c.keywords.slice(0,2).join('与')}`).join('；')}。把这些线索当作观察当下的切面，而非确定的预言。</p>`;$('#readingSummary').classList.add('visible')}
$('#readingCards').addEventListener('click',e=>{const card=e.target.closest('.floating-card');if(!card)return;if(card.classList.contains('revealed')&&readingPhase==='interpretation')openDetail(currentReading,Number(card.dataset.readIndex));else revealCard(card)});
$('#revealAll').addEventListener('click',async()=>{if(!['selection','reveal'].includes(readingPhase))return;for(const card of $$('.floating-card:not(.revealed)')){revealCard(card);await wait(230)}});
$('#redraw').addEventListener('click',async()=>{if(isAnimating)return;isAnimating=true;$$('.floating-card').forEach((el,i)=>{el.style.setProperty('--exitX',`${(i%2?-1:1)*(180+i*22)}px`);el.classList.add('exiting')});await wait(480);closeScene($('#readingScene'));isAnimating=false;await wait(180);openReading()});

function filterDeck(){const q=$('#cardSearch').value.trim().toLowerCase();filteredCards=cards.filter(c=>(activeSuit==='all'||c.suit===activeSuit)&&(!q||`${c.name}${c.en}${c.keywords.join('')}`.toLowerCase().includes(q)));deckIndex=Math.min(deckIndex,Math.max(0,filteredCards.length-1));renderDeck()}
$('#cardSearch').addEventListener('input',filterDeck);$$('.filters button').forEach(btn=>btn.addEventListener('click',()=>{activeSuit=btn.dataset.suit;$$('.filters button').forEach(x=>x.classList.toggle('active',x===btn));deckIndex=0;filterDeck()}));
function renderDeck(direction=0){const focus=$('#deckFocus'),track=$('#deckTrack');if(!filteredCards.length){focus.innerHTML='<div class="empty-state">没有找到匹配的牌<br><small>TRY ANOTHER SIGNAL</small></div>';track.innerHTML='';$('#deckCount').textContent='00 / 00';return}const c=filteredCards[deckIndex];focus.classList.remove('shift-next','shift-prev');void focus.offsetWidth;if(direction)focus.classList.add(direction>0?'shift-next':'shift-prev');focus.innerHTML=`<button class="focus-card" aria-label="查看${c.name}完整释义">${art(c)}</button><div class="focus-copy"><span>${c.suitName} / ${String(cards.indexOf(c)).padStart(2,'0')}</span><h2>${c.name}</h2><h3>${c.en}</h3><div>${c.keywords.map(k=>`<b>${k}</b>`).join('')}</div><p>${c.meaning}</p><button class="text-button">查看正位 / 逆位完整释义 →</button></div>`;const offsets=[-2,-1,0,1,2];track.innerHTML=offsets.map(off=>{const idx=(deckIndex+off+filteredCards.length)%filteredCards.length,item=filteredCards[idx];return `<button class="track-card ${off===0?'current':''}" data-index="${idx}" style="--offset:${off};--track-delay:${Math.abs(off)*35}ms">${art(item)}<span>${item.name}</span></button>`}).join('');$('#deckCount').innerHTML=`<b>${String(deckIndex+1).padStart(2,'0')}</b> / ${String(filteredCards.length).padStart(2,'0')}`}
function moveDeck(step){if(!filteredCards.length)return;deckIndex=(deckIndex+step+filteredCards.length)%filteredCards.length;renderDeck(step)}
$('.deck-arrow.prev').addEventListener('click',()=>moveDeck(-1));$('.deck-arrow.next').addEventListener('click',()=>moveDeck(1));$('#deckTrack').addEventListener('click',e=>{const item=e.target.closest('.track-card');if(!item)return;const next=Number(item.dataset.index),dir=next===deckIndex?0:(next>deckIndex?1:-1);deckIndex=next;renderDeck(dir)});$('#deckFocus').addEventListener('click',e=>{if(e.target.closest('.focus-card,.text-button'))openDetail(filteredCards,deckIndex)});let wheelLock=false;$('#deck').addEventListener('wheel',e=>{if(!$('#deck').classList.contains('active-view')||wheelLock)return;e.preventDefault();wheelLock=true;moveDeck(e.deltaY>0?1:-1);setTimeout(()=>wheelLock=false,320)},{passive:false});

function openDetail(context,index){detailContext=context;detailIndex=index;renderDetail(0);openScene($('#detailScene'))}
function renderDetail(direction){const item=detailContext[detailIndex],card=item.sourceIndex!==undefined?cards[item.sourceIndex]:item,reversed=Boolean(item.isReversed);const cardWrap=$('#detailCard'),info=$('#detailInfo');cardWrap.className=`detail-card ${direction>0?'swap-next':direction<0?'swap-prev':''}`;info.className=`detail-info ${direction>0?'swap-next':direction<0?'swap-prev':''}`;info.dataset.title=card.name;cardWrap.innerHTML=`${art(card,reversed?'detail-reversed':'')}<span>${reversed?'REVERSED':'UPRIGHT'}</span>`;info.innerHTML=`<span class="detail-code">ARCANA / ${card.suitName}</span><h2>${card.name}</h2><h3>${card.en}</h3><div class="detail-keywords">${card.keywords.map(k=>`<b>${k}</b>`).join('')}</div><section><h4>${reversed?'逆位解释':'正位解释'}</h4><p>${reversed?card.reversed:card.meaning}</p></section><section class="alternate"><h4>${reversed?'正位参考':'逆位参考'}</h4><p>${reversed?card.meaning:card.reversed}</p></section>`}
function moveDetail(step){detailIndex=(detailIndex+step+detailContext.length)%detailContext.length;renderDetail(step)}
$('.detail-prev').addEventListener('click',()=>moveDetail(-1));$('.detail-next').addEventListener('click',()=>moveDetail(1));$('.detail-close').addEventListener('click',()=>closeScene($('#detailScene')));

function setRitualStep(id){$$('.ritual-step').forEach(x=>x.classList.toggle('active',x.id===id))}
function startRitual(){openScene($('#ritual'));setRitualStep('ritualAsk');setTimeout(()=>$('#ritualQuestion').focus(),500)}
$('#ritualQuestion').addEventListener('input',e=>$('#ritualCounter').textContent=`${e.target.value.length} / 80`);
$('#ritualContinue').addEventListener('click',runRitual);$('#ritualQuestion').addEventListener('keydown',e=>{if(e.key==='Enter')runRitual()});
async function runRitual(){setRitualStep('ritualShuffle');await wait(1850);renderChoice();setRitualStep('ritualResult')}
function renderChoice(){currentChoices=randomDraw(2);const q=$('#ritualQuestion').value.trim();$('#ritualTopic').textContent=q?`关于「${q}」`:'关于你此刻面对的选择';$('#choiceCards').innerHTML=currentChoices.map((c,i)=>`<article class="choice-card ${c.isReversed?'is-reversed':''}" style="--delay:${i*180}ms"><button data-choice-index="${i}" aria-label="查看${c.name}完整解释"><span>方向 ${i?'B':'A'}</span>${art(c)}</button><section><span>${c.en}</span><h3>${c.name} · ${c.isReversed?'逆位':'正位'}</h3><div>${c.keywords.map(k=>`<b>${k}</b>`).join('')}</div><p>${c.isReversed?c.reversed:c.meaning}</p></section></article>`).join('')}
$('#choiceCards').addEventListener('click',e=>{const button=e.target.closest('[data-choice-index]');if(button)openDetail(currentChoices,Number(button.dataset.choiceIndex))});
$('#ritualRedraw').addEventListener('click',async()=>{if(isAnimating)return;isAnimating=true;$('#choiceCards').classList.add('reshuffling');await wait(500);setRitualStep('ritualShuffle');await wait(1500);renderChoice();$('#choiceCards').classList.remove('reshuffling');setRitualStep('ritualResult');isAnimating=false});$('.ritual-close').addEventListener('click',()=>closeScene($('#ritual')));$('#ritualDone').addEventListener('click',()=>closeScene($('#ritual')));
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const top=$('.detail-scene.open')||$('.reading-scene.open')||$('.ritual.open');if(top)closeScene(top);return}if($('.detail-scene.open')){if(e.key==='ArrowLeft')moveDetail(-1);if(e.key==='ArrowRight')moveDetail(1);return}if($('#deck').classList.contains('active-view')&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){if(['ArrowLeft','ArrowUp'].includes(e.key))moveDeck(-1);if(['ArrowRight','ArrowDown'].includes(e.key))moveDeck(1);if(e.key==='Enter'&&filteredCards.length)openDetail(filteredCards,deckIndex)}});
renderDeck();
